Add comments, tests for proxies
The ABC declaration was a bit misleading. Now a comment has been added to explain that
Python 2 does not implement the ABC class directly, but only the ABCMeta class.

Some tests have been added to check that TransformationProxy instances return the correct
node attributes when they are called. For instance, if a transformation operation is called
on a proxy, it will create a new proxy to a node holding that operation. On the other hand,
if a node class attribute is called on a proxy, this should return the proxied node attribute.
Finally, if a non-defined attribute is called on a proxy, this should raise an `AttributeError`.

The pickling test has been modified. While before it tested that the `__getstate__` method of
the TransformationProxy class was called when issuing a pickle.dumps() on the proxy, now it
tests that pickling a proxy raises a `pickle.PickleError`, since we are not providing that
functionality at the moment.