Improve attribute errors on RDataFrame or Operation objects
New error messages better reflect the source of error when a user calls a non existing attribute on a node of the graph. Between Python 2 and 3 there are differences in the management of the stack trace:

Python2:
```
>>> import PyRDF
>>> a = PyRDF.RDataFrame(10)
>>> a.random
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "PyRDF/Proxy.py", line 128, in __getattr__
    raise AttributeError(msg)
AttributeError: 'RDataFrame' object has no attribute 'random'
>>> a.Define("x","tdfentry_").random
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "PyRDF/Proxy.py", line 128, in __getattr__
    raise AttributeError(msg)
AttributeError: 'Define' object has no attribute 'random'
```

Python 3:
```
>>> import PyRDF
>>> a = PyRDF.RDataFrame(10)
>>> a.random
Traceback (most recent call last):
  File "/home/PyRDF/PyRDF/Proxy.py", line 117, in __getattr__
    return getattr(self.proxied_node, attr)
AttributeError: 'HeadNode' object has no attribute 'random'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/PyRDF/PyRDF/Proxy.py", line 128, in __getattr__
    raise AttributeError(msg)
AttributeError: 'RDataFrame' object has no attribute 'random'
>>> a.Define("x","tdfentry_").random
Traceback (most recent call last):
  File "/home/PyRDF/PyRDF/Proxy.py", line 117, in __getattr__
    return getattr(self.proxied_node, attr)
AttributeError: 'Node' object has no attribute 'random'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/PyRDF/PyRDF/Proxy.py", line 128, in __getattr__
    raise AttributeError(msg)
AttributeError: 'Define' object has no attribute 'random'
```

So that in Python 3 the error caught at the `except` statement is shown as well.